## Sample .travis.yml file for use with metacran/r-builder
## See https://github.com/metacran/r-builder for details.

language: c
sudo: required

before_install:
  - curl -OL https://raw.githubusercontent.com/metacran/r-builder/master/pkg-build.sh
  - chmod 755 pkg-build.sh
  - ./pkg-build.sh bootstrap

install:
  - ./pkg-build.sh install_deps

script:
  - ./pkg-build.sh run_tests

after_failure:
  - ./pkg-build.sh dump_logs

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7e17d054ef1002b3e128
    on_success: change
    on_failure: always
    on_start: never

env:
  matrix:
    - RVERSION=oldrel
    - RVERSION=release
    - RVERSION=devel
